runtime: nodejs16
env: standard
instance_class: F1
handlers:
- url: /
  secure: always
  static_files: app/index.html
  upload: app/index.html
- url: /(.*)
  secure: always
  static_files: app/\1
  upload: app/(.*)
- url: .*
  script: auto
- url: .*
  script: auto
